# Generated by Django 4.1.6 on 2023-02-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='name',
            new_name='trait_name',
        ),
    ]
