# Generated by Django 4.1.6 on 2023-02-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_rename_trait_name_trait_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
